# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ahmed Ali
email: byahmedali@gmail.com
tagline: Building Intelligent Data-Driven Solutions
description: >- # this means to ignore newlines until "baseurl:"
  Ahmed Ali is an AI and Data Science professional with expertise in Microsoft Azure, Python, and Power BI.
  This portfolio showcases his hands-on projects, research publications, and training work in applied AI,
  machine learning, and data analytics. Explore how Ahmed builds intelligent, data-driven solutions to
  real-world challenges using modern cloud technologies.
linkedin_username: byahmedali
github_username: byahmedali
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ahmed Ali"
  avatar : "/assets/images/picture.jpg"
  bio    : "AI & Data Science Practitioner."
  links:
  - label: "LinkedIn"
    icon: "fa-brands fa-linkedin" 
    url: "https://www.linkedin.com/in/byahmedali/"
  - label: "GitHub"
    icon: "fa-brands fa-github"
    url: "https://github.com/byahmedali"
  - label: "Google Scholar"
    icon: "fa-brands fa-google-scholar"
    url: "https://scholar.google.com/citations?user=YSRvNhoAAAAJ&hl"


footer:
  links:
  - label: "LinkedIn"
    icon: "fa-brands fa-linkedin" 
    url: "https://www.linkedin.com/in/byahmedali/"
  - label: "GitHub"
    icon: "fa-brands fa-github"
    url: "https://github.com/byahmedali"
  - label: "Google Scholar"
    icon: "fa-brands fa-google-scholar"
    url: "https://scholar.google.com/citations?user=YSRvNhoAAAAJ&hl"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
