# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ""
email: "byahmedali@gmail.com"
tagline: "Building Intelligent Data-Driven Solutions"
description: "Ahmed Ali is an AI and Data Science professional with expertise in Microsoft Azure, Python, and Power BI.
  This portfolio showcases his hands-on projects, research publications, and training work in applied AI,
  machine learning, and data analytics. Explore how Ahmed builds intelligent, data-driven solutions to
  real-world challenges using modern cloud technologies."
image: "/assets/images/preview.png"
url: "https://byahmedali.github.io"
linkedin_username: "byahmedali"
github_username: "byahmedali"
minimal_mistakes_skin: "mint" # "air", "mint", "dark", "neon"
search: true
markdown: "kramdown"
remote_theme: "mmistakes/minimal-mistakes"
locale: "en-US"
timezone: Asia/Karachi
repository: "byahmedali/byahmedali.github.io"
logo: "/assets/images/byahmedaliteal.png"

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

collections:
  projects:
    output: true
    permalink: /projects/:path/
  publications:
    output: true
    permalink: /publications/:path/

include:
  - _pages

assets:
  css:
    - /assets/css/custom.css

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ahmed Ali"
  avatar : "/assets/images/profile.jpg"
  bio    : "AI & Data Science Professional • Microsoft Certified: Azure Data Scientist & Administrator • Power BI Data Analyst & Trainer • Traveler & Photographer"
  links:
  - label: "LinkedIn"
    icon: "fa-brands fa-linkedin" 
    url: "https://www.linkedin.com/in/byahmedali/"
  - label: "GitHub"
    icon: "fa-brands fa-github"
    url: "https://github.com/byahmedali"
  - label: "Google Scholar"
    icon: "fa-brands fa-google-scholar"
    url: "https://scholar.google.com/citations?user=YSRvNhoAAAAJ&hl"
  - label: "Email"
    icon: "fa-solid fa-envelope"
    url: "mailto:byahmedali@gmail.com"
  - label: "Instagram"
    icon: "fa-brands fa-instagram"
    url: "https://www.instagram.com/byahmedali/"


footer:
  links:
  - label: "LinkedIn"
    icon: "fa-brands fa-linkedin" 
    url: "https://www.linkedin.com/in/byahmedali/"
  - label: "GitHub"
    icon: "fa-brands fa-github"
    url: "https://github.com/byahmedali"
  - label: "Google Scholar"
    icon: "fa-brands fa-google-scholar"
    url: "https://scholar.google.com/citations?user=YSRvNhoAAAAJ&hl"
  - label: "Email"
    icon: "fa-solid fa-envelope"
    url: "mailto:byahmedali@gmail.com"
  - label: "Instagram"
    icon: "fa-brands fa-instagram"
    url: "https://www.instagram.com/byahmedali/"


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/